apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml


configMapGenerator:
- files:
  - game-settings.properties
  name: game-config
labels:
- includeSelectors: true
  pairs:
    app: kube-roguelite
