apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- grafana.yaml


configMapGenerator:
- files:
  - game-settings.properties
  name: game-config
labels:
- includeSelectors: true
  pairs:
    app: kube-roguelite

images:
- name: grafana
  newTag: "12.1"

patches:
- patch: |-
    - op: replace
      path: /spec/resources/requests/storage
      value: 2 Gi 
  target:
    kind: PersistentVolumeClaim
